# Generated by Django 2.2.2 on 2019-07-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0002_auto_20190709_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='filter',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
