# Generated by Django 2.2.2 on 2019-07-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0003_auto_20190709_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Filter (e.g. Bill, News, Opinion e.t.c)', max_length=200)),
            ],
        ),
    ]
