# Generated by Django 2.2.2 on 2019-07-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0004_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='filter',
            field=models.ManyToManyField(help_text='Select a filter for this article', to='testsite.Filter'),
        ),
    ]
